# image will be published to ghcr.io/<user>/<name>
name: plasmasix
# description will be included in the image's metadata
description: This is my personal OS image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 39 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - usr: /usr
          # copy static configurations
          #
          # copies config/files/usr into your image's /usr
          #
          # configuration you wish to end up in /etc/ on the booted system
          # should be added into /usr/etc/ as that is the proper "distro"
          # config directory on ostree. Read more in the files module's README

  - type: rpm-ostree
    repos:        
      - https://copr.fedorainfracloud.org/coprs/elxreno/preload/repo/fedora-rawhide/elxreno-preload-fedora-rawhide.repo
    install:
       - micro
       - fish
       - btop
       - cargo
       - pipx
       - adw-gtk3-theme
       - fira-code-fonts
       - irqbalance
       - profile-sync-daemon  
       - prelockd
       - preload
       - corectrl
       - prismlauncher
       - armcord
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      # repo-title: "Flathub (system-wide)" # Optional; this sets the remote's user-facing name in graphical frontends like GNOME Software
      install: 
               - org.gnome.Loupe
               - com.alientrap.nexuiz-classic
               - com.github.GradienceTeam.Gradience
               - com.github.huluti.Curtail
               - com.github.marhkb.Pods
               - com.github.rafostar.Clapper
               - com.github.tchx84.Flatseal
               - com.github.unrud.VideoDownloader
               - com.github.wwmm.easyeffects
               - com.mattjakeman.ExtensionManager
               - com.obsproject.Studio
               - com.spotify.Client
               - io.github.giantpinkrobots.flatsweep
               - io.lmms.LMMS
               - net.cubers.assault.AssaultCube
               - net.davidotek.pupgui2
               - net.waterfox.waterfox
               - org.bluesabre.MenuLibre
               - org.gimp.GIMP
               - org.gnome.Calculator
               - org.gnome.Calendar
               - org.gnome.Characters
               - org.gnome.Contacts
               - org.gnome.Epiphany
               - org.gnome.Evince
               - org.gnome.Loupe
               - org.gnome.Maps
               - org.gnome.Music
               - org.gnome.Snapshot
               - org.gnome.TextEditor
               - org.gnome.Totem
               - org.gnome.Weather
               - org.gnome.clocks
               - org.gnome.font-viewer
               - org.gustavoperedo.FontDownloader
               - org.kde.kdenlive
               - org.kde.krita
               - org.mozilla.firefox
               - org.sauerbraten.Sauerbraten
               - org.srb2.SRB2
               - org.srb2.SRB2Kart
               - org.supertuxproject.SuperTux
               - org.xonotic.Xonotic
               - page.codeberg.libre_menu_editor.LibreMenuEditor
               - pm.mirko.Atoms
               - org.gtk.Gtk3theme.adw-gtk3
               - org.gtk.Gtk3theme.adw-gtk3-dark
               - org.freedesktop.Platform.VulkanLayer.gamescope//23.08
               - org.freedesktop.Platform.ffmpeg-full//23.08         

      # - one.ablaze.floorp//lightning # This is an example of flatpak which has multiple branches in selection (flatpak//branch).
      # Flatpak runtimes are not supported (like org.winehq.Wine//stable-23.08).
      # Only normal flatpak applications are (like Floorp Lightning web browser in this example).
      # Multiple install of same flatpaks with different branches is not supported.
      remove:
        # - org.gnome.eog
        #
        # A flatpak repo can also be added without having to install flatpaks,
        # as long as one of the repo- fields is present
    user:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
  - type: fonts
    fonts:
     nerd-fonts:
      - FiraCode # don't add "Nerd Font" suffix.
      - Hack
      - SourceCodePro
      - Terminus
      - JetBrainsMono
      - NerdFontsSymbolsOnly
     google-fonts:
      - Roboto
      - Open Sans
      - Fira Sans
      - Fira Mono
      - Fira Code

  - type: systemd
    system:
     enabled:
      - preload.service 
      - prelockd.service 
      - fstrim.timer
     disabled:
      - NetworkManager-wait-online.service
    user:
     enabled:
        psd.service

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
